project:
  type: book


filters:
  - include-code-files

book:
  title: "GeneralEquilibriumModeling.jl and Structural Equilibrium Models"
  subtitle: "A Cookbook"
  site-url: "https://liwur.github.io/GEMBook/"
  google-analytics: "G-5XKP5QW2FE"
  cookie-consent: true  
  author:
    - name: "LI Wu (liwu@staff.shu.edu.cn)"
      email: "liwu@staff.shu.edu.cn"
  date: "2026-09-10"
  chapters:
    - index.qmd
    - Ch1SEM.qmd
    - Ch2GEM.qmd
    - Ch3PureExch.qmd
    - Ch4ProdBasic.qmd
    - Ch5ProdExtended.qmd
    - Ch6Intertemporal.qmd
    - references.qmd

# bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
    latex-tinytex: true
    latex-auto-install: false
    keep-tex: true
    include-in-header:
      - text: |
          \AtBeginDocument{\floatplacement{codelisting}{H}}
