project:
  type: book

book:
  title: "General Equilibrium Modeling: From Structural Equilibrium Models to GEMB.jl"
  author: "LI Wu"
  date: "2026/8/25"
  chapters:
    - index.qmd
    #- intro.qmd
    - Ch1SEM.qmd
    - summary.qmd
    - references.qmd

# bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



